### ISSUE TITLE
火狐浏览器下幻灯片图片选择模块没加载出来

### ISSUE THREAD

**Issue by hui-ho** [guojiangclub/ecommerce-open-api#26]
- 版本：2.0.3
- 问题：火狐浏览器下幻灯片图片选择模块没加载出来

![图片](https://user-images.githubusercontent.com/28501148/68822991-69b8c300-06cd-11ea-9a2f-cc1e91192464.png)

**Comment by shjchen** [comment]
因为命名问题，页面名称中包含 ad 关键词，导致被谷歌 Adblock 插件及类似插件屏蔽导致，关闭即可。

请检查 firefox 是否有类似 Adblock 的插件，有的话，请关闭。
